spring:
  profiles: dev
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
custom:
  message: Hello, api-dev!
---
spring:
  profiles: st
  rabbitmq:
    host: st.eomdev.com
    port: 5672
    username: stUser
    password: stPassword
    virtual-host: vhost02
server:
  port: 9999
custom:
  message: Hello, api ST!
---
spring:
  profiles: prod
  rabbitmq:
    host: eomdev.com
    port: 5672
    username: user
    password: password
    virtual-host: vhost03
custom:
  message: Hello, api prod!