spring:
  profiles:
    active: native
server:
  port: 8888
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/IdeaProjects/study/blog-samples/config-repo
  rabbitmq:
    host: 192.168.99.100
    username: guest
    password: guest
    port: 5672
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ['bus-refresh']
---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/umsh86/blog-samples.git
          search-paths: config-repo